// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzlmVyIGfIWkpq3b82jI7qz-D5rmDOGBM',
    appId: '1:607137638331:web:c3b2fc22e3c993d9c9869e',
    messagingSenderId: '607137638331',
    projectId: 'e-commerce-4efc1',
    authDomain: 'e-commerce-4efc1.firebaseapp.com',
    storageBucket: 'e-commerce-4efc1.appspot.com',
    measurementId: 'G-GDJ01GNEDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMh5uVvOhtb4-O5TroYeAgutsLPb2pf7Q',
    appId: '1:607137638331:android:7121d314bc285499c9869e',
    messagingSenderId: '607137638331',
    projectId: 'e-commerce-4efc1',
    storageBucket: 'e-commerce-4efc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY-72mkQCMHCoJTRKDHR1QBYfDE2-aTJ0',
    appId: '1:607137638331:ios:54f7c73163b7d5efc9869e',
    messagingSenderId: '607137638331',
    projectId: 'e-commerce-4efc1',
    storageBucket: 'e-commerce-4efc1.appspot.com',
    iosClientId: '607137638331-acdcq0jq5suripvc8v5qpdbnq85t3v9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY-72mkQCMHCoJTRKDHR1QBYfDE2-aTJ0',
    appId: '1:607137638331:ios:54f7c73163b7d5efc9869e',
    messagingSenderId: '607137638331',
    projectId: 'e-commerce-4efc1',
    storageBucket: 'e-commerce-4efc1.appspot.com',
    iosClientId: '607137638331-acdcq0jq5suripvc8v5qpdbnq85t3v9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
